### ISSUE TITLE
`import badger2040` results in OSError: [Errno 5] EIO

### ISSUE THREAD

**Issue by kvchen** [pimoroni/badger2040#38]
After flashing my 2040W with the latest firmware (0.0.3), attempting to import badger2040 now results in an EIO error:

```
>>> import badger2040
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "badger2040.py", line 57, in <module>
OSError: [Errno 5] EIO
```

I can also repro this by entering commands into the repl: it appears that these lines trigger it in the firmware:

```
>>> import machine
>>> i2c = machine.I2C(0)
>>> i2c.writeto_mem(0x51, 0x00, b'\x00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 5] EIO
```

**Comment by kvchen** [comment]
My bad, I was using the wrong firmware (2040W instead of 2040). Closing this issue out.
